[CLNASS_101 신재훈] MainPageView 생성
wecode-bootcamp-korea/14-2nd-CLNASS101-backend pull request #15
Opened 2020-12-10 07:46 UTC by NoahShin

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-10 13:07 UTC, lordmyshepherd requested changes

2020-12-10 13:07 UTC, lordmyshepherd commented on product/views.py
> +            }
dictionary comprehension을 활용해서 조금 더 유연한 filter 기능을 구현할 수 있습니다. 아래 코드를 참고해보세요~
나중에 코드를 리펙토링할 때 적용해보세요~
```python
filter_prefixes = { 
		'types'       : 'types__name__in',
		'max_num_ppl' : 'maximum_number_of_people__lte'
}

filter_set = {filter_prefixes.get(key) : value for (key, value) in dict(request.GET).items()}
```

2020-12-10 13:07 UTC, lordmyshepherd commented on product/views.py
> +                return JsonResponse({'MESSAGE': 'KEY_ERROR'}, status=400)
이렇게되면 sorting 값을 무조건 받아야 되지 않나요??

2020-12-10 13:07 UTC, lordmyshepherd commented on product/views.py
> +                'isLiked'     : True if ProductLike.objects.filter(product_id=product.id).exists() else False,
product 부터 접근해서 구현해보세요.
```suggestion
                'isLiked'     : True if product.xxxx else False,
```

2020-12-10 15:59 UTC, NoahShin commented on product/views.py
> +            }
오.. 나중에 공부하고 리팩토링 하겠습니다 감사합니다!

2020-12-10 15:59 UTC, NoahShin commented on product/views.py
> +                return JsonResponse({'MESSAGE': 'KEY_ERROR'}, status=400)
네 소팅값 안받으면 에러 나게 했습니다.

2020-12-10 16:37 UTC, NoahShin commented on product/views.py
> +                return JsonResponse({'MESSAGE': 'KEY_ERROR'}, status=400)
무조건 받는걸로 프론트랑 소통하면 안될까요??

2020-12-10 17:00 UTC, NoahShin commented on product/views.py
> +                return JsonResponse({'MESSAGE': 'KEY_ERROR'}, status=400)
아 무조건 안받게 지웠습니다.

2020-12-10 17:01 UTC, NoahShin commented on product/views.py
> +                'isLiked'     : True if ProductLike.objects.filter(product_id=product.id).exists() else False,
접근해보았는데, 아직로그인 안한 상태이기 때문에 모두 False로 넣었고, 로그인 한 상태이면 어떡할지 아직 모르겠습니다.

2020-12-11 00:16 UTC, lordmyshepherd commented on product/views.py
> +                'isLiked'     : True if ProductLike.objects.filter(product_id=product.id).exists() else False,
재훈님!! 로그인 한 상태에서 보여주는 products와 로그인 하지 않은 상태에서 보여주는 products가 필요하다고 하면,
엔드포인트를 분리하시면 될 것 같아요!

2020-12-11 02:54 UTC, NoahShin commented on product/views.py
> +                'isLiked'     : True if ProductLike.objects.filter(product_id=product.id).exists() else False,
네 알겠습니다!

2020-12-11 03:51 UTC, lordmyshepherd commented
LGTM 👍

2020-12-11 03:51 UTC, merged