[CLNASS_101 신재훈] SignUpView 생성
wecode-bootcamp-korea/14-2nd-CLNASS101-backend pull request #2
Opened 2020-12-03 05:01 UTC by NoahShin

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
소셜 로그인 말고, 웹사이트 클나쓰101에 회원가입할 때 API

- 회원가입시 필요한 내용
이름       : 1자 이상 20자 이하 특정조건없음
이메일    : @, .  이메일 형식만 지키면 가능
비밀번호 : 8자 이상 25자 이하 특정조건없음 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- core 앱 생성
- core 앱 안에 utils.py 에 get_hashed_pw, is_valid_name, is_valid_email, is_valid_password & login_decorator 생성
- 로그인 데코레이터는 추후 사용 예정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 지금 올린 PR에서 로그인 데코레이터는 쓰지 않는데.. 그럼 지워서 올리는 것이 맞나요? 아니면 쓴김에 올리나요? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있고 팀원들한테 코드리뷰 받고, 컨벤션 맞추고, 수정함
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-03 07:29 UTC, soheon-lee commented
@NoahShin 재훈님 코드 잘 작성하셨네요 :) Unit Test 붙여주세요~

2020-12-04 06:49 UTC, jamessoun93 requested changes

2020-12-04 06:49 UTC, jamessoun93 commented on user/tests.py
> +        })
매번 append 하는것보다 requests 리스트 생성할 때 한번에 넣어서 선언해주는게 낫지 않을까요?

2020-12-04 06:49 UTC, jamessoun93 commented on user/views.py
> +        )
Exception 핸들링 추가해주세요. 이렇게 마무리되면 해당 코드 중 에러발생 시 서버가 멈추게 됩니다.

2020-12-04 06:49 UTC, jamessoun93 commented on user/views.py
> +
여기도 Exception 핸들링 추가해주세요.

2020-12-04 08:01 UTC, NoahShin commented on user/tests.py
> +        })
수정했습니다.

2020-12-05 06:02 UTC, closed without merging