[CLNASS_101 신재훈] SignUpView, LogInView, KakaoLogInView > UserApp 로 합침
wecode-bootcamp-korea/14-2nd-CLNASS101-backend pull request #4
Opened 2020-12-05 05:42 UTC by NoahShin

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
1. LogInView 유닛테스트 할 때 SignUpView가 필요하고
2. SignUpView를 작성할 때 함수로 뺀다고 Core 앱을 만들고 거기에 utils.py를 생성
3.  로컬 develop 으로  다시가서 feature/LogInView 브랜치를 만드니까 새 브랜치에 core앱이 없는 상황..(signupview가 머지가 빨리되면 이 프로세스가 괜찮겠지만, 사실상 힘든현실)
4.  그래서 소헌님 허락받고 SignUpView에서 LogInView 브랜치를 만들고 작성,
5.  kakaologInView도 loginview에서 브랜치를 만들고 작성
6. 4번 5번을 하다보니 git rebase를 했는데, 코드가 막 SignUpView, LoginView 때로 돌아가버려서 새로 쓴 코드가 없어지는 현상 발생
(브랜치를 develop에서 새로 안만들어서 그런듯)
7. 3시간동안 눈물의 git꼬쇼 후, 겨우 복귀
8. 리뷰하는데 번거롭게 해드려서 죄송합니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 멘토 리뷰 반영 (유닛테스트 수정 및 views.py 에러핸들링 try/except로 모두 수정)
- 3개의 view 합침

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- product/models.py 수정사항 한줄 고쳤는데 귀신같이 rebase할 때 마다 따라다님, 아마도 develop에서 고쳐서 그런가요

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-05 12:19 UTC, jamessoun93 requested changes

2020-12-05 12:19 UTC, jamessoun93 commented on .vscode/settings.json
> +}
에디터관련 설정 파일은 팀원 전체적으로 함께 사용하실것이 아니라면 `git`에 올리실때 포함시키지 말아주세요~

2020-12-05 12:19 UTC, jamessoun93 commented on user/views.py
> +from core.utils  import get_hashed_pw, is_valid_name, is_valid_email, is_valid_password, checkpw, issue_token
import 해야할 유틸 함수들이 많은 관계로 한줄로 처리하는 것보다 소괄호를 이용해 여러줄로 구분지어주시면 좋을 것 같네요.

2020-12-05 12:19 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({'MESSAGE':'DUPLICATED_INFORMATION'}, status=400)
```suggestion
                return JsonResponse({'MESSAGE':'DUPLICATE_INFORMATION'}, status=400)
```

2020-12-05 12:19 UTC, jamessoun93 commented on user/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_PASSWORD'}, status=400)
```suggestion
                return JsonResponse({'MESSAGE':'INVALID_PASSWORD'}, status=401)
```

2020-12-05 12:19 UTC, jamessoun93 commented on user/views.py
> +            user     = User.objects.get(email=data['email'])
여기서는 하나의 user 객체를 가져오는것이 목적이기 때문에 질문하신대로 `get` 이 불필요한 추가코드를 없애줄 수 있고 (filter 로 가져오는 경우 인덱스로 또 접근해야하기 때문), 잡아놓으신 `DoesNotError` 로도 캐치할 수 있겠네요.

2020-12-05 12:19 UTC, jamessoun93 commented on user/views.py
> +            url          = 'https://kapi.kakao.com/v2/user/me'
- 이런 `constant` 는 바뀌는 값이 아니기때문에 주로 이런 것들만 모아놓는 파일에서 import 해서 사용하는 경우가 많습니다. (효율적인 관리를 위해 그리고 다른 로직에서도 쓸 가능성이 높을때)
- 그리고 `constant` 는 변수명을 대문자로 지어주는 것이 `convention` 입니다 👍

2020-12-05 12:19 UTC, jamessoun93 commented on user/views.py
> +            header       = {
```suggestion
            headers       = {
```
원래 `headers` 가 맞으니 여기도 헷갈리지 않게 `headers` 라고 선언해주세요.

2020-12-05 12:19 UTC, jamessoun93 commented on user/views.py
> +            print("===================================================")
이메일이 안오는 문제 관련해서 stackoverflow 게시글 확인했습니다. 이메일까지 없다면 유저에 대한 정보가 너무 없는 상황인데 이메일을 못받아오는 상황은 오래된 이메일이라고 못받아오는게 사실 조금 이상해서 이 부분은 직접 조금 연구해보고 말씀드리겠습니다.

2020-12-05 14:34 UTC, NoahShin commented on .vscode/settings.json
> +}
네 죄송합니다. 분명 gitignore에 올렸던걸로 기억하는데, 수정하겠습니다.

2020-12-05 14:38 UTC, NoahShin commented on .vscode/settings.json
> +}
![Screen Shot 2020-12-05 at 11 37 06 PM](https://user-images.githubusercontent.com/69205911/101245820-dbd5cd00-3752-11eb-989a-ad5ceda4b201.png)
여기 이렇게 쓰는 것 말고 다르게 써서 적용 시킬 방법이 있을까요?

2020-12-05 14:39 UTC, NoahShin commented on user/views.py
> +from core.utils  import get_hashed_pw, is_valid_name, is_valid_email, is_valid_password, checkpw, issue_token
네 수정했습니다

2020-12-05 14:40 UTC, NoahShin commented on user/views.py
> +                return JsonResponse({'MESSAGE':'DUPLICATED_INFORMATION'}, status=400)
아 지금 회워가입 할 때니까.. 알겠습니다.

2020-12-05 14:42 UTC, NoahShin commented on user/views.py
> +                return JsonResponse({'MESSAGE':'INVALID_PASSWORD'}, status=400)
유닛테스트도 수정했습니다.

2020-12-05 14:43 UTC, NoahShin commented on user/views.py
> +            user     = User.objects.get(email=data['email'])
답변 감사합니다.

2020-12-05 14:46 UTC, NoahShin commented on user/views.py
> +            url          = 'https://kapi.kakao.com/v2/user/me'
- 다음에 다른곳에서도 쓰는 constant 쓸 일 이 생기면(이번 프젝에서는 더 이상 안쓰일 것 같아서..) 다른 파일로 옮기고 import해서 사용하겠습니다.
- 네, 대문자로 수정했습니다.

2020-12-05 14:47 UTC, NoahShin commented on user/views.py
> +            header       = {
앗.. 오히려 headers = headers 하면 읽을 때 헷갈릴까바 뺏는데,, 오히려 똑같이 하는게 좋군요

2020-12-05 14:50 UTC, NoahShin commented on user/views.py
> +            print("===================================================")
![IMG_20201204_232322](https://user-images.githubusercontent.com/69205911/101246092-623ede80-3754-11eb-8c7a-4761d348b1ab.jpg)
아 두연님이랑 머리 맞대고 해결할려고 했는데, 두연님이 현지님 access_token 받고 했더니 됬습니다.
아마도 상혁님이 세팅했을 때 쵸큼 문제가 있었나 봐요. 월요일에 같이 한번 다시 붙여보고 들어오는 형식보고 다시 짤 계획입니다. (사실 두연님이 보내주신 사진 보고 짜긴 했는데, 이제 get_or_create 문제입니다. flag 를 잘 이해를 못해서 튜플의 첫번째인 [0] 써서 만들었습니다.

2020-12-05 15:03 UTC, jamessoun93 commented on .vscode/settings.json
> +}
`**/.vscode/` 이렇게 추가해주셔야 될거에요 재훈님!

2020-12-05 15:23 UTC, NoahShin commented on .vscode/settings.json
> +}
오 감사합니다. 바로 수정하겠습니다.

2020-12-05 16:25 UTC, jamessoun93 commented
@NoahShin 재훈님 지금 모든 migration 파일들과 몇몇 models.py 코드에 충돌난 상태로 올라왔는데 확인부탁드립니다.

2020-12-06 00:39 UTC, NoahShin commented
![Screen Shot 2020-12-06 at 9 31 27 AM](https://user-images.githubusercontent.com/69205911/101268471-862b1000-37a6-11eb-81d5-4b1468093d0c.png)
이게 충돌코드인거같은데.. 뭐가 충돌인지 안나옵니다. >>>HEAD 이런게 없어요..
![Screen Shot 2020-12-06 at 9 35 51 AM](https://user-images.githubusercontent.com/69205911/101268474-a064ee00-37a6-11eb-8416-c5b4972e3783.png)
그리고 저 signiture 오타수정... 3일째 따라다니는데,, git rebase 정상적으로 하면  저 커밋 나타나고, 저거 없앨려고 rebase하면 ㅋㅋㅋㅋㅋㅋㅋ 코드 저때로 돌아가고 ㅎㅎ
(signature 오타 수정 << 아마 로컬develop에서 커밋한거 일거 같구요,
그 상태에서 branch를 만들었으니, 새 브랜치 git rebase 할때 따라오는 flow 같은데,..)
제가 졌습니다. 그냥 다 백업하고 다 싹다 지우고 새로 시작 하면 안될까요

2020-12-07 08:07 UTC, closed without merging