Add: 새로만든 User app
wecode-bootcamp-korea/14-2nd-CLNASS101-backend pull request #6
Opened 2020-12-07 08:39 UTC by NoahShin

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 새로 브랜치 파서 Core App 지우고, 그냥 패키지 형식으로 다시 만들었습니다.
- Kakao Unit Test 아직 못함, 제가 상혁님이랑 붙여봤는데 400 떠서 상혁님 코드 수정 필요,
제가 원하는 정보 다 뽑아온 다음에 Unit Test 해보겠습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2020-12-08 07:39 UTC, lordmyshepherd requested changes

2020-12-08 07:39 UTC, lordmyshepherd commented on core/utils.py
> +    return jwt.encode({'user_id': user_id}, SECRET['secret'], algorithm=ALGORITHM['algorithm']).decode('UTF-8')
모듈화 하는 시도는 굉장히 좋은 것 같습니다!
다만 간단한(한줄) 로직을 호출하기 위해서 함수 객체가 생성되기 때문에 분리할 필요가 없을 것 같습니다.

2020-12-08 07:39 UTC, lordmyshepherd commented on user/tests.py
> +        self.assertEqual(response.status_code, 400)
duplicate error code는 `409`입니다.
```suggestion
        self.assertEqual(response.status_code, 409)
```

2020-12-08 07:39 UTC, lordmyshepherd commented on user/views.py
> +            print("===================================================")
print문은 지워주세요!

2020-12-08 07:39 UTC, lordmyshepherd commented on user/views.py
> +            ACCESS_TOKEN = request.headers["Authorization"]
상수가 아니라 변수로 선언해주세요.
```suggestion
            kakao_access_token = request.headers["Authorization"]
```

2020-12-08 07:39 UTC, lordmyshepherd commented on user/views.py
> +            user = User.objects.get(kakao_id=kakao_user["id"])
get() 호출시, matching되는 query가 존재하지 않을 경우 발생할 수 있는 에러를 핸들링해주세요!

2020-12-08 07:39 UTC, lordmyshepherd commented on user/views.py
> +            user = User.objects.get(kakao_id=kakao_user["id"])
93에서 User 인스턴스를 가져오는데 다시 get으로 조회하는 이유가 있으신가요?

2020-12-09 01:11 UTC, NoahShin commented on core/utils.py
> +    return jwt.encode({'user_id': user_id}, SECRET['secret'], algorithm=ALGORITHM['algorithm']).decode('UTF-8')
네 다음부터 이런 한줄 로직은 분리하지 않겠습니다.

2020-12-09 01:20 UTC, NoahShin commented on user/views.py
> +            ACCESS_TOKEN = request.headers["Authorization"]
그.. 저번에 피드백 받았을때, 변수로 했다가.. URL 이나 access_token( 시간 남아서 소셜 하나 이상 더 할 경우 상수가 되기 때문에) 을 상수로 하라고 피드백 받아서 상수로 고쳤습니다. 근데 시간이 남지않아서 카카오만 할거같은데 다시 변수로 고칠까요?

2020-12-09 05:30 UTC, lordmyshepherd commented on user/views.py
> +            ACCESS_TOKEN = request.headers["Authorization"]
고정 상수가 아니기 때문에, 변수로 지정해주세요~

2020-12-09 09:53 UTC, NoahShin reviewed
어떤 리뷰는 제가 답장이 안되게 되어있는데 이럴때느 어떡하죠? 그리고 리뷰 반영해서 상수를 변수로 고쳐서 올렸는데, 
제가 새로운 리뷰를 못 찾은건지 수정요청으로 라벨로 바뀌었습니다.

2020-12-09 09:53 UTC, NoahShin commented on user/views.py
> +            user = User.objects.get(kakao_id=kakao_user["id"])
- 네 에러 핸들링 해보겠습니다.
- 앗, 반복코드 지우겠습니다

2020-12-09 10:30 UTC, NoahShin commented on user/tests.py
> +        self.assertEqual(response.status_code, 400)
수정헀습니다

2020-12-09 10:31 UTC, NoahShin commented on user/views.py
> +            print("===================================================")
네 수정했습니다

2020-12-09 11:56 UTC, lordmyshepherd approved these changes

2020-12-09 11:56 UTC, lordmyshepherd commented
LGTM 👍

2020-12-09 11:57 UTC, merged